#!/usr/bin/env perl

use strict;
use warnings;

Groups->run(
	table             => 'core.groups',
	selectable_fields => [ 'id', 'group_name' ],
	updatable_fields => [ 'group_name' ],
	sortable_fields  => [ 'id',   'group_name' ],
);

package Groups;

use lib '/opt/nibelite/lib/perl';
use base 'Nibelite::App::CRUD';

1;
